/* ===========================================================================
   ANCHORAGE — render functions
   ---------------------------------------------------------------------------
   A render function is a fold consumer that emits a non-EO output format.
   It consults Lens DEFs of a chosen `framework` value, walks anchors with
   relevant Lens projections, and emits OWL / JSON-LD / RDF / whatever.

   Per spec: each render is one-way and lossy. Anchors without a relevant
   Lens DEF are dropped from the render with a logged note. The drops are
   diagnostic — they tell the user what the target framework can't represent
   in this corpus.

   Public surface:
     AnchorageRender.targets                — list of registered targets
     AnchorageRender.run(target, projection) — { text, mime, filename, drops }
       drops = { dropped: [aid,...], byTerrain: {key->n}, total, kept }

   Each render reads the active fold projection — it does not call the fold
   itself. Switching Horizon then re-running render produces a different
   projection without re-extraction, per spec.
============================================================================ */

(function (global) {
  'use strict';

  function escapeTtl(s) {
    return String(s == null ? '' : s).replace(/[\\"]/g, c => '\\' + c)
                                     .replace(/[\r\n]+/g, ' ');
  }
  function isoStamp() {
    return new Date().toISOString();
  }

  // -------------------------------------------------------------
  // Drop accounting helper.
  //
  // For a given projection and framework, walk every anchor; an anchor
  // is "kept" if any DEF stack at kind=lens has an opKey 'lens:<framework>'.
  // Anchors without such a DEF are recorded as drops and bucketed by
  // their dominant terrain so the notes panel can show *what* the target
  // framework can't reach in this corpus.
  // -------------------------------------------------------------
  function collectByLens(projection, framework) {
    const T = global.AnchorageTerrains;
    const kept = [];
    const dropped = [];
    const byTerrain = Object.create(null);
    for (const aid of Object.keys(projection.anchors || {})) {
      const stacks = (projection.defStacks || {})[aid] || {};
      const lens = stacks.lens || {};
      const matched = !!lens['lens:' + framework];
      if (matched) {
        const last = lens['lens:' + framework].slice(-1)[0];
        kept.push({ aid, lensEvent: last });
      } else {
        const t = T.dominantTerrain((projection.cellPopulations || {})[aid] || {});
        const tk = t ? t.key : 'unknown';
        byTerrain[tk] = (byTerrain[tk] || 0) + 1;
        dropped.push(aid);
      }
    }
    return {
      kept,
      drops: {
        dropped,
        byTerrain,
        total: dropped.length,
        kept: kept.length
      }
    };
  }

  // -------------------------------------------------------------
  // BFO render — minimal Turtle (.ttl).
  //
  // Each kept anchor becomes:
  //   <prefix:aid> a bfo:<Category> ;
  //                rdfs:label "<aid>" ;
  //                anchorage:terrain "<terrain.key>" .
  //
  // The substrate has no schema for BFO categories — we forward whatever
  // the Lens DEF's operand carries. If the convention is wrong the output
  // is wrong; that's the convention's responsibility, not the substrate's.
  // -------------------------------------------------------------
  function renderBfo(projection) {
    const T = global.AnchorageTerrains;
    const { kept, drops } = collectByLens(projection, 'bfo');
    const lines = [
      '@prefix bfo: <http://purl.obolibrary.org/obo/bfo.owl#> .',
      '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .',
      '@prefix anchorage: <https://anchorage.local/ns#> .',
      '@prefix : <https://anchorage.local/anchor/> .',
      '',
      '# Generated by AnchorageRender.run("bfo") at ' + isoStamp(),
      '# Anchors emitted: ' + kept.length + '   Anchors dropped: ' + drops.total,
      ''
    ];
    for (const { aid, lensEvent } of kept) {
      const op = lensEvent.operand || {};
      const cat = op.category || 'IndependentContinuant';
      const subcat = op.subcategory || null;
      const t = T.dominantTerrain((projection.cellPopulations || {})[aid] || {});
      const safeId = aid.replace(/[^a-zA-Z0-9_]/g, '_');
      lines.push(':' + safeId + ' a bfo:' + cat + ' ;');
      if (subcat) lines.push('  bfo:hasSubcategory "' + escapeTtl(subcat) + '" ;');
      lines.push('  rdfs:label "' + escapeTtl(aid) + '" ;');
      if (t) lines.push('  anchorage:terrain "' + t.key + '" ;');
      lines.push('  anchorage:lensRationale "' + escapeTtl(lensEvent.rationale || '') + '" .');
      lines.push('');
    }
    return {
      text: lines.join('\n'),
      mime: 'text/turtle',
      filename: 'anchorage-bfo-' + isoStamp().replace(/[:.]/g, '-') + '.ttl',
      drops,
      framework: 'bfo'
    };
  }

  // -------------------------------------------------------------
  // DOLCE render — same shape, different prefix.
  // -------------------------------------------------------------
  function renderDolce(projection) {
    const T = global.AnchorageTerrains;
    const { kept, drops } = collectByLens(projection, 'dolce');
    const lines = [
      '@prefix dolce: <http://www.loa.istc.cnr.it/dolce/dolce.owl#> .',
      '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .',
      '@prefix anchorage: <https://anchorage.local/ns#> .',
      '@prefix : <https://anchorage.local/anchor/> .',
      '',
      '# Generated by AnchorageRender.run("dolce") at ' + isoStamp(),
      '# Anchors emitted: ' + kept.length + '   Anchors dropped: ' + drops.total,
      ''
    ];
    for (const { aid, lensEvent } of kept) {
      const op = lensEvent.operand || {};
      const cat = op.category || 'PhysicalEndurant';
      const t = T.dominantTerrain((projection.cellPopulations || {})[aid] || {});
      const safeId = aid.replace(/[^a-zA-Z0-9_]/g, '_');
      lines.push(':' + safeId + ' a dolce:' + cat + ' ;');
      lines.push('  rdfs:label "' + escapeTtl(aid) + '" ;');
      if (t) lines.push('  anchorage:terrain "' + t.key + '" ;');
      lines.push('  anchorage:lensRationale "' + escapeTtl(lensEvent.rationale || '') + '" .');
      lines.push('');
    }
    return {
      text: lines.join('\n'),
      mime: 'text/turtle',
      filename: 'anchorage-dolce-' + isoStamp().replace(/[:.]/g, '-') + '.ttl',
      drops,
      framework: 'dolce'
    };
  }

  // -------------------------------------------------------------
  // schema.org render — JSON-LD.
  //
  // Each kept anchor becomes a JSON-LD object with the schema.org type
  // from its Lens DEF.
  // -------------------------------------------------------------
  function renderSchemaOrg(projection) {
    const T = global.AnchorageTerrains;
    const { kept, drops } = collectByLens(projection, 'schema.org');
    const graph = kept.map(({ aid, lensEvent }) => {
      const op = lensEvent.operand || {};
      const t = T.dominantTerrain((projection.cellPopulations || {})[aid] || {});
      const node = {
        '@type': op.type || 'Thing',
        '@id': 'https://anchorage.local/anchor/' + aid,
        'name': aid,
        'identifier': aid
      };
      if (t) node['additionalType'] = 'anchorage:' + t.key;
      // Forward any schema.org-style fields verbatim from the operand.
      for (const k of Object.keys(op)) {
        if (k !== 'framework' && k !== 'type' && !(k in node)) node[k] = op[k];
      }
      return node;
    });
    const doc = {
      '@context': {
        '@vocab': 'https://schema.org/',
        'anchorage': 'https://anchorage.local/ns#'
      },
      '@graph': graph
    };
    return {
      text: JSON.stringify(doc, null, 2),
      mime: 'application/ld+json',
      filename: 'anchorage-schema-' + isoStamp().replace(/[:.]/g, '-') + '.jsonld',
      drops,
      framework: 'schema.org'
    };
  }

  // -------------------------------------------------------------
  // CSV render — tabular dump. Special: doesn't gate on Lens DEFs;
  // every anchor gets a row. Drops are always 0.
  // -------------------------------------------------------------
  function renderCsv(projection) {
    const T = global.AnchorageTerrains;
    const rows = ['aid,terrain,dominant_cell,obs_count,def_count,first_seen'];
    for (const aid of Object.keys(projection.anchors || {}).sort()) {
      const cells = (projection.cellPopulations || {})[aid] || {};
      const obs = Object.values(cells).reduce((s, n) => s + n, 0);
      const stacks = (projection.defStacks || {})[aid] || {};
      const defs = Object.values(stacks).reduce(
        (s, kindMap) => s + Object.values(kindMap).reduce((s2, stk) => s2 + stk.length, 0), 0);
      const t = T.dominantTerrain(cells);
      const top = Object.entries(cells).sort((a, b) => b[1] - a[1])[0];
      const cell = top ? top[0] : '';
      const fs = (projection.anchors[aid] || {}).first_seen || '';
      rows.push([
        csvEsc(aid),
        csvEsc(t ? t.name : ''),
        csvEsc(cell),
        obs,
        defs,
        csvEsc(fs)
      ].join(','));
    }
    return {
      text: rows.join('\n') + '\n',
      mime: 'text/csv',
      filename: 'anchorage-table-' + isoStamp().replace(/[:.]/g, '-') + '.csv',
      drops: { dropped: [], byTerrain: {}, total: 0, kept: rows.length - 1 },
      framework: 'csv'
    };
  }
  function csvEsc(v) {
    const s = String(v == null ? '' : v);
    if (/[,"\n]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
    return s;
  }

  // -------------------------------------------------------------
  // Native .eo passthrough.
  //
  // Lets the render dropdown be the single export entry point in the UI.
  // The native render is lossless by definition — drops always 0.
  // -------------------------------------------------------------
  function renderNative(projection, ctx) {
    const events = (ctx && ctx.getEvents) ? ctx.getEvents() : [];
    const text = global.EOFormat.serializeEoFile(events);
    return {
      text, mime: 'application/x-ndjson',
      filename: 'anchorage-' + isoStamp().replace(/[:.]/g, '-') + '.eo',
      drops: { dropped: [], byTerrain: {}, total: 0, kept: events.length },
      framework: 'native'
    };
  }

  const targets = [
    { key: 'native',     name: 'Anchorage native (.eo)', run: renderNative },
    { key: 'bfo',        name: 'BFO (.ttl)',             run: renderBfo },
    { key: 'dolce',      name: 'DOLCE (.ttl)',           run: renderDolce },
    { key: 'schema.org', name: 'schema.org (.jsonld)',   run: renderSchemaOrg },
    { key: 'csv',        name: 'Tabular (.csv)',         run: renderCsv }
  ];

  function run(targetKey, projection, ctx) {
    const t = targets.find(x => x.key === targetKey);
    if (!t) throw new Error('AnchorageRender.run: unknown target ' + targetKey);
    return t.run(projection, ctx || {});
  }

  global.AnchorageRender = { targets, run };
})(typeof window !== 'undefined' ? window : globalThis);
